services:
  front:
    build: ./front
    ports:
      - 3333:5173
    volumes:
      - ./front/react-app:/app/react-app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true